/*
 * File: app/store/CampaniasMysql.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.CampaniasMysql', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Campanias',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CampaniasMysql',
            model: 'MyApp.model.Campanias',
            proxy: {
                type: 'ajax',
                extraParams: {
                    sql: 'SELECT id,codigo,descripcion FROM periodos'
                },
                url: 'php/listado.php',
                reader: {
                    type: 'json',
                    rootProperty: 'reqList'
                }
            }
        }, cfg)]);
    }
});