/*
 * File: app/store/LaboresMysql.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.LaboresMysql', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Labores',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'LaboresMysql',
            autoLoad: false,
            model: 'MyApp.model.Labores',
            proxy: {
                type: 'ajax',
                extraParams: {
                    sql: 'select l.id,fecha,cod_lote_actividad,cod_lote,cod_area,cod_establecimiento,cod_periodo,cod_tarea,l.cantidad,precio_tarea,cod_contratista, t.descrip as nombre_labor from labores l JOIN tareas t ON l.cod_tarea = t.codigo'
                },
                url: 'php/listado.php',
                reader: {
                    type: 'json',
                    rootProperty: 'reqList'
                }
            }
        }, cfg)]);
    }
});