/*
 * File: app/view/actividadesGrid.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.actividadesGrid', {
    extend: 'Ext.container.Container',
    alias: 'widget.actividadesgrid',

    requires: [
        'MyApp.view.establecimientosGridViewModel1',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'actividadesgrid'
    },
    height: 250,
    id: 'actividadesGrid',
    itemId: 'actividadesGrid',
    width: 400,
    layout: 'card',

    items: [
        {
            xtype: 'gridpanel',
            dock: 'top',
            itemId: 'actividadesGrid',
            rtl: false,
            style: 'padding: 5px 5px 5px 5px;\ncolor: #424242;',
            bodyStyle: 'color: #424242;',
            glyph: 'xf06c@FontAwesome',
            iconAlign: 'left',
            title: 'Actividades',
            titleAlign: 'left',
            autoLoad: true,
            bufferedRenderer: false,
            forceFit: true,
            store: 'Actividades',
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: '20%',
                    dataIndex: 'codigo',
                    text: 'Codigo',
                    format: '00'
                },
                {
                    xtype: 'gridcolumn',
                    width: '80%',
                    dataIndex: 'nombre',
                    text: 'Nombre'
                }
            ]
        }
    ]

});