/*
 * File: app/view/configPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.configPanel', {
    extend: 'Ext.container.Container',
    alias: 'widget.configPanel',

    requires: [
        'MyApp.view.establecimientosGridViewModel15',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'configpanel'
    },
    id: 'configPanel',
    itemId: 'configPanel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            itemId: 'login',
            bodyPadding: 10,
            title: 'Datos de Conexión',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'usuarioImp',
                    fieldLabel: '',
                    value: 'Admin',
                    inputId: 'usuarioInp',
                    emptyText: 'Usuario'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'claveImp',
                    fieldLabel: '',
                    value: 'Synagro',
                    emptyText: 'Clave'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'baseImp',
                    fieldLabel: '',
                    emptyText: 'Base'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'servidorImp',
                    fieldLabel: '',
                    value: 'sistec01.dnsalias.com',
                    emptyText: 'Servidor'
                }
            ]
        },
        {
            xtype: 'toolbar',
            flex: 0,
            height: 60,
            itemId: 'laboresFoterTlb',
            style: 'background-color:#424242;',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    itemId: 'aceptarConexionbtn',
                    glyph: 'xf019@FontAwesome',
                    iconCls: '',
                    text: 'Grabar'
                },
                {
                    xtype: 'button',
                    id: 'cancelBtn2',
                    itemId: 'cancelBtn',
                    params: 'alert',
                    text: 'Cancelar'
                }
            ]
        }
    ]

});