/*
 * File: app/view/Mensaje.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Mensaje', {
    extend: 'Ext.window.Window',
    alias: 'widget.Mensaje',

    requires: [
        'MyApp.view.MensajeViewModel',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'mensaje'
    },
    modal: true,
    height: 250,
    width: 400,
    title: 'Mensaje',

    items: [
        {
            xtype: 'label',
            itemId: 'msjContent',
            margin: '10px 10px 10px 10px',
            padding: '10px 10px 10px 10px',
            text: 'My Label'
        }
    ],

    f_mensaje: function(title, msg) {
         this.setTitle(title);
         this.down('#msjContent').setText(msg);
    }

});