/*
 * File: app/view/SincPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SincPanel', {
    extend: 'Ext.container.Container',
    alias: 'widget.sync',

    requires: [
        'MyApp.view.establecimientosGridViewModel12',
        'Ext.panel.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.form.Label',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'sincpanel'
    },
    id: 'SincPanel',
    itemId: 'SincPanel',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            flex: 1,
            itemId: 'sincronizar',
            title: 'Sincronizar',
            items: [
                {
                    xtype: 'fieldset',
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'tabla',
                            fieldLabel: 'Tablas'
                        }
                    ]
                },
                {
                    xtype: 'label',
                    itemId: 'estado_sinc',
                    text: 'Estado: '
                }
            ]
        },
        {
            xtype: 'toolbar',
            flex: 0,
            height: 60,
            itemId: 'laboresFoterTlb',
            style: 'background-color:#424242;',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    itemId: 'aceptarLaboresbtn',
                    glyph: 'xf01a@FontAwesome',
                    iconCls: '',
                    text: 'Iniciar',
                    listeners: {
                        click: 'onAceptarLaboresbtnClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'cancelBtn1',
                    itemId: 'cancelBtn',
                    params: 'alert',
                    text: 'Cancelar'
                }
            ]
        }
    ],

    onAceptarLaboresbtnClick: function(button, e, eOpts) {
        var panel = Ext.ComponentQuery.query('#SincPanel')[0];
        panel.f_sincronizar();
    },

    f_sincronizar: function() {
         f_sinc.agregar_todas();
         debugger;
         f_sinc.sincronizar();
    }

});