/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Actividades',
        'Campanias',
        'Contratistas',
        'Depositos',
        'Establecimientos',
        'Insumos',
        'Lotes',
        'Maquinaria',
        'Personal',
        'Rubros',
        'Tareas',
        'Lotes_actividades',
        'Labores',
        'Labores_insumos',
        'Labores_personal',
        'Labores_maquinaria',
        'Registros_borrados',
        'Secuencia',
        'Lotes_coordenadas'
    ],
    stores: [
        'ActividadesMysql',
        'CampaniasMysql',
        'ContratistasMysql',
        'DepositosMysql',
        'EstablecimientosMysql',
        'InsumosMysql',
        'LotesMysql',
        'MaquinariaMysql',
        'PersonalMysql',
        'RubrosMysql',
        'TareasMysql',
        'actividadeslotesStore',
        'Lotes_actividadesMysql',
        'LaboresMysql',
        'Labores_insumosMysql',
        'lotesStore',
        'establecimientosStore',
        'Labores_personalMysql',
        'Labores_maquinariaMysql',
        'Campanias',
        'Contratistas',
        'Depositos',
        'Establecimientos',
        'Insumos',
        'Labores_insumos',
        'Labores_maquinaria',
        'Labores_personal',
        'Lotes',
        'Labores',
        'Lotes_actividades',
        'Maquinaria',
        'Personal',
        'Registros_borrados',
        'Rubros',
        'Secuencia',
        'Tareas',
        'Actividades',
        'Lotes_coordenadas',
        'Lotes_coordenadasMysql'
    ],
    views: [
        'main',
        'menuPrincipal',
        'establecimientosGrid',
        'actividadesGrid',
        'lotesGrid',
        'campaniasGrid',
        'tareasGrid',
        'personalGrid',
        'rubroinsumosGrid',
        'insumosGrid',
        'maquinariasGrid',
        'contratistasGrid',
        'depositosGrid',
        'menuTabla',
        'actividadeslotesGrid',
        'laboresGrid',
        'laboresForm',
        'configPanel',
        'Mensaje'
    ],
    controllers: [
        'buttonsActions',
        'viewRenders',
        'comboxActions',
        'gridActions',
        'acordionActions'
    ],
    name: 'MyApp',

    launch: function() {
        Ext.create('MyApp.view.main');
        debugger;
        MyApp.archivo_base = 'Agrimanager';
        MyApp.screen_count = 0;
        MyApp.screen_name = [];
        //MyApp.url_lib     = '../LibPHP/';
        MyApp.url_lib       = 'http://inforeports.dnsalias.com/LibPHP/';
        MyApp.usuario       = window.localStorage.getItem("agrimanager_usuario");
        MyApp.clave         = window.localStorage.getItem("agrimanager_clave");
        MyApp.base_nombre   = window.localStorage.getItem("agrimanager_base");
        MyApp.base_url      = window.localStorage.getItem("agrimanager_servidor");
        MyApp.base_usuario  = 'dba';
        MyApp.base_clave    = 'gestion525';
        MyApp.estado_sinc   = '';
        MyApp.lote			= '';
        MyApp.sinc_array_store = [];
        MyApp.sinc_array_tabla = [];
        MyApp.estado_editar = 'N';
        f_crud.load_store('Registros_borrados');
        f_crud.load_store('Tareas');
        f_crud.load_store('Actividades');
        f_crud.load_store('Campanias');
        f_crud.load_store('Establecimientos');
        f_crud.load_store('Insumos');
        f_crud.load_store('Lotes');
        f_crud.load_store('Lotes_coordenadas');
        f_crud.load_store('Rubros');
        f_crud.load_store('Personal');
        f_crud.load_store('Maquinaria');
        f_crud.load_store('Contratistas');
        f_crud.load_store('Depositos');
        //----- controlo que exista un registro en secuencia
        var sql ='select count(id) as cant from secuencia';
        f_crud.load_store('Secuencia','','',function(rtn){
            f_crud.sql_select(sql,function(array){
                var cant = array[0].cant;
                if (cant===0){
                    f_crud.sql_command('Insert into secuencia (id,secuencia) values (1,1)', function(rtn){
                        console.log('Insert en tabla secuencia = ',rtn);
                    } );
                }
            });
        });
        document.addEventListener("backbutton", onBackKeyDown, false);

        function onBackKeyDown() {
            if ( MyApp.main.getComponent('lotesgrid')===MyApp.main.getActiveItem() || MyApp.screen_count===0 ) {
                Ext.Msg.show({
                    title:'Desea salir de la aplicacion ?',
                    buttons: [{text: 'Si'},{text: 'No'}],
                    fn: opcion
                });

            }
            else {
                MyApp.screen_count-- ;
                MyApp.main.setActiveItem( MyApp.screen_name[MyApp.screen_count] );
            }
            function opcion(btn) {
                if (btn=='Si'){navigator.app.exitApp();}
            }
        }
    }

});
