/*
 * File: app/controller/comboxActions.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.comboxActions', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control({
            'combobox#establecimientosCbo': {
                select: 'onEstablecimientosSelect'
            },
            'combobox#lotesCbo': {
                select: 'onLotesSelect'
            },
            'combobox#cod_tarea': {
                select: 'ontareaLaboresSelect'
            }
        });
    },

    onEstablecimientosSelect: function(combo, record, eOpts) {
        debugger;
        var lotesCbo = Ext.ComponentQuery.query('#lotesCbo')[0];
        lotesCbo.enable();
        lotesCbo.clearValue();
        f_crud.load_store("Lotes");
        var lotesactStore = Ext.getStore("Lotes");
        console.log(lotesactStore);
        var codigo = record.data.codigo;
        lotesactStore.filter('cod_establecimiento',codigo);
        lotesCbo.bindStore(lotesactStore);
        lotesCbo.displayField = 'nombre';
        lotesCbo.valueField = 'codigo';
    },

    onLotesSelect: function(combo, record, eOpts) {
        var actLotesGrid = Ext.ComponentQuery.query('#actividadesGrid')[0];
        var establecimientoCbo = Ext.ComponentQuery.query('#establecimientosCbo')[0];
        actLotesGrid.enable();
        f_crud.load_store("Lotes_actividades");
        var actLotesStore = Ext.getStore("Lotes_actividades");
        var cod_lote = record.data.codigo;
        var cod_est  = establecimientoCbo.value;
        actLotesStore.filter('cod_lote',cod_lote);
        actLotesStore.filter('cod_establecimiento',cod_est);
        console.log(actLotesStore);
        actLotesGrid.bindStore(actLotesStore);
    },

    ontareaLaboresSelect: function(combo, record, eOpts) {
        var labBtn = Ext.ComponentQuery.query('#aceptarLaboresbtn')[0];
        labBtn.enable();
    }

});
