/*
 * File: app/controller/gridActions.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.gridActions', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control({
                    'gridpanel#actividadesGrid': {
                        rowclick: this.onActividadesGridRowClic
                    }
                });
    },

    onActividadesGridRowClic: function(tableview, record, tr, rowIndex, e, eOpts) {
        debugger;
        var laboresGrid = Ext.create("MyApp.view.laboresGrid")[0];
        var laboresListGrid = Ext.ComponentQuery.query('#laboresListGrid')[0];
        var codigo = record.data.codigo;
        f_crud.load_store("Labores");
        var Labores = Ext.getStore('Labores');
        Labores.filter('cod_lote_actividad',codigo);
        laboresListGrid.bindStore(Labores);
        MyApp.lote = codigo;
        //var laboresForm = Ext.create("MyApp.view.laboresForm")[0];
        //var loteLab = Ext.ComponentQuery.query('#loteLabInp')[0];
        //console.log(loteLab);
        //loteLab.setValue(codigo);
        var cmp = Ext.ComponentQuery.query('#laboresGrid')[0];
        if(!cmp){
            var cmp = Ext.create("MyApp.view.laboresGrid")[0];
            MyApp.main.add(cmp);
        }
        MyApp.main.getLayout().setActiveItem(cmp);
    }

});
