/*
 * File: app/controller/viewRenders.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.viewRenders', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control({
            'container#contenedorPrincipal': {
                beforerender: this.onContenedorPrincipalBeforeRender
            },
            'container#menuTablas': {
                beforerender: this.onmenuTablasBeforeRender
            },
            'container#configPanel': {
                beforerender: this.onConfigPanelBeforeRender
            },
            'gridpanel#depositoGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#actividadesGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#campaniasGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#contratistasGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#insumosGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#lotesGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#maquinariasGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#personalGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#tareasGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'gridpanel#rubroinsumosGrid': {
                beforerender: this.onGridpanelBeforeRender
            },
            'panel#labPanel': {
                beforerender: this.onLabPanelBeforeRender
            }
        });
    },

    onContenedorPrincipalBeforeRender: function(component, eOpts) {
        MyApp.main = component;
        var cmp = Ext.ComponentQuery.query("#menuPrincipal")[0];
        if(!cmp){
            var cmp = Ext.create('MyApp.view.menuPrincipal');
            MyApp.main.add(cmp);
        }
        MyApp.main.getLayout().setActiveItem(cmp);
    },

    onmenuTablasBeforeRender: function(component, eOpts) {
            var btn = Ext.ComponentQuery.query('#returnView')[0];
            btn.hide();
    },

    onFormExpand: function(p, eOpts) {
        var labTlb = Ext.ComponentQuery.query("#laboresFoterTlb")[0];
        console.log(labTlb);
        labTlb.hide();
    },

    onConfigPanelBeforeRender: function(component, eOpts) {

        debugger;
        var usuarioImp = Ext.ComponentQuery.query("#usuarioImp")[0];
        var claveImp = Ext.ComponentQuery.query("#claveImp")[0];
        var baseImp = Ext.ComponentQuery.query("#baseImp")[0];
        var servidorImp = Ext.ComponentQuery.query("#servidorImp")[0];


        var usuario =window.localStorage.getItem("agrimanager_usuario");
        var clave = window.localStorage.getItem("agrimanager_clave");
        var base = window.localStorage.getItem("agrimanager_base");
        var servidor = window.localStorage.getItem("agrimanager_servidor");

        usuarioImp.setValue(usuario);
        claveImp.setValue(clave);
        baseImp.setValue(base);
        servidorImp.setValue(servidor);
                if(!window.localStorage.getItem("agrimanager_usuario")) {
                    usuarioImp.setValue('Admin');
                }
                if(!window.localStorage.getItem("agrimanager_clave")) {
                    claveImp.setValue('Synagro');
                }
                if(!window.localStorage.getItem("agrimanager_servidor")) {
                    servidorImp.setValue('sistec01.dnsalias.com');
                }
                if(!window.localStorage.getItem("agrimanager_base")) {
                    baseImp.setValue('');
                }
    },

    onGridpanelBeforeRender: function(component, eOpts) {
                        debugger;
                        var store = component.getStore();
                        var storeName = store.id;
                        f_crud.load_store(storeName);
    },

    onLabPanelBeforeRender: function(component, eOpts) {
        console.log(MyApp.lote);
        var loteLab = Ext.ComponentQuery.query('#codigo_lote_actividad')[0];
        loteLab.setValue(MyApp.lote);
        debugger;
        var store = Ext.getStore('Lotes_actividades');
        var num = store.find('codigo',MyApp.lote);
        console.log(num);
        if (num==-1) {return '...';}
        else { loteLab.setValue(store.getAt(num).get('nombre'));}
    }

});
